// src/frontend/ts/App/App.tsx
import 'whatwg-fetch';

import React from "react";

import Header from './_partials/Header';
import Footer, { SocialLink } from './_partials/Footer';

import IssueTracker from './Components/IssueTracker/_index';
import ExperienceOverview, { HistoryEntry } from './Components/ExperienceOverview/_index';
import { FilterEntries } from './Components/ExperienceOverview/Filter';

export interface AppState {
    filter : FilterEntries
    isssueTrackerIsActive : boolean
    history: HistoryEntry[] 
    socialLinks: SocialLink[]
}

export default class App extends React.Component<any, AppState> {

    constructor(props : any, context : any) {
        super(props, context);
        
        this.state = {
            isssueTrackerIsActive: false,
            history: [],
            socialLinks: [],
            filter: {
                tags: ['interested'],
                level: 200
            },
        }

        this.handleFilterChange = this.handleFilterChange.bind(this);
        this.handleFeedbackClick = this.handleFeedbackClick.bind(this);
    }

    render() {
        return (
            <div className="App">
                <Header />
                    <div className="App_Main">
                        <div className="Textarea">
                            <div className="Textarea_Block">
                                <h2>Welcome!</h2>
                                <p>
                                    here you have the possibillity to get an insight into my skillset.<br />
                                    For example here are some predefined filters.
                                </p>
                                <div className="LayoutContainer">
                                    <div className="LayoutContainer_ElementWrapper LayoutContainer_ElementWrapper-Half">
                                        <p>
                                            To watch my learned skills and those im interested in <button className="button button_small" onClick={() => this.handleFilterChange(300, ['interested'])}>click here!</button>
                                        </p>
                                    </div>
                                    <div className="LayoutContainer_ElementWrapper LayoutContainer_ElementWrapper-Half">
                                        <p>
                                            Show only the skills, i have masterd and work with them on a daily basis <button className="button button_small" onClick={() => this.handleFilterChange(500, [])}>click here!</button>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <ExperienceOverview data={this.state.history} filter={this.state.filter} />
                    <div className="Textarea">
                        <h2>Imprint</h2>
                        <p>
                            grizzly.web (Sebastian Müller)<br />
                            Ostwall 125<br />
                            47798 Krefeld<br />
                        </p>
                        <p>
                            Owner: Sebastian Müller<br />
                            identification number: 942/0588/6738<br />
                        </p>
                    </div>
                    <IssueTracker isActive={this.state.isssueTrackerIsActive} onClose={this.handleFeedbackClick}/>
                </div>
                <Footer socialLinks={this.state.socialLinks} onFeedbackClick={this.handleFeedbackClick}/>
            </div>
        )
    }

    componentDidMount() {
        this.fetchData().then((data) => {
            this.setState(
                Object.assign(this.state, data)
            );
        });
    }

    handleFilterChange(level : number, tags : string[]) {
        this.setState({
            ...this.state,
            filter: {
                tags: tags,
                level: level
            }
        }, () => {
            console.log(this.state)
            
            this.forceUpdate();
        });

    }

    handleFeedbackClick(e : React.MouseEvent<HTMLButtonElement>) {
        this.setState({
            ...this.state,
            isssueTrackerIsActive: !this.state.isssueTrackerIsActive
        });

        e.preventDefault();
    }

    fetchData() {
        return fetch('/content/data.json').then((response) => {
            return response.json().then((data) => {
                return data;
            })
        });
    }

}

// src/App.vue
<template>
  <div class="App">
    <header class="App_Header">
      <div class="container">
        <h2 class="h1">Skills & References</h2>
        <a class="logo" href="/">
          <h1>
            <span class="name">
              Sebastian<br />
              Müller
            </span>
            <span class="company">{spanPerCharacter('grizzly.web')}</span>
          </h1>
        </a>
      </div>
    </header>

      <div class="App_Main">
        <!-- <ExperienceOverview data={this.state.history} filter={this.state.filter} ></ExperienceOverview> -->
        <div class="Textarea">
          <h2>Imprint</h2>
          <p>
            grizzly.web (Sebastian Müller)<br />
            Ostwall 125<br />
            47798 Krefeld<br />
          </p>
          <p>
            Owner: Sebastian Müller<br />
            identification number: 942/0588/6738<br />
          </p>
        </div>
        <!--<IssueTracker isActive={this.state.isssueTrackerIsActive} onClose={this.handleFeedbackClick}></IssueTracker>-->
      </div>
      <!-- <Footer socialLinks={this.state.socialLinks} onFeedbackClick={this.handleFeedbackClick}></Footer> -->
      <footer class="App_Footer">
        <div class="container">
          <div class="social-links">
            <h4>you find me on</h4>
            {socialLinks}
          </div>
          <nav class="meta-nav">
            <h4>about this website</h4>
            <button this.props.onFeedbackClick>Feedback / Bug report</button>
            <a href="https://github.com/grizzlydotweb/grizzly-dot-web-career" target="_blank">Opensource (github.com)</a>
          </nav>
        </div>
      </footer>
  </div>
</template>

<script>

export default {
  name: 'app',
  components: {
  }
}
</script>
